runtime: python38
service: default
instance_class: F1
default_expiration: "24h"
automatic_scaling:
  max_instances: 1
  max_concurrent_requests: 40
handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
- url: /.*
  script: auto
env_variables:
  CONFIG_SETTINGS: "app.config.ProductionConfig"