runtime: python38
service: api
instance_class: F1
default_expiration: "24h"
automatic_scaling:
  max_instances: 1
  max_concurrent_requests: 40
handlers:
- url: /.*
  script: auto
env_variables:
  CONFIG_SETTINGS: "config.ProductionConfig"